// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3DONa2lwALDtCeHoYOgjf2ClgvEIh6Z0',
    appId: '1:913978065914:web:8dad9f762b6155e5b35a43',
    messagingSenderId: '913978065914',
    projectId: 'ecommerce-app-c97b9',
    authDomain: 'ecommerce-app-c97b9.firebaseapp.com',
    storageBucket: 'ecommerce-app-c97b9.firebasestorage.app',
    measurementId: 'G-WBEJ0Z9SLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfqZq-65iiIuk0LoOBhsu3V5UL5Y3HQfA',
    appId: '1:913978065914:android:2f79cb852719c16bb35a43',
    messagingSenderId: '913978065914',
    projectId: 'ecommerce-app-c97b9',
    storageBucket: 'ecommerce-app-c97b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxnNrDRlhZ_ZEQr4y52XvnAtfFyLCtiT0',
    appId: '1:913978065914:ios:3ac347ddefafa87eb35a43',
    messagingSenderId: '913978065914',
    projectId: 'ecommerce-app-c97b9',
    storageBucket: 'ecommerce-app-c97b9.firebasestorage.app',
    androidClientId: '913978065914-hbc57tjs6nmmjsp2ipdcjrgtlq1au7en.apps.googleusercontent.com',
    iosClientId: '913978065914-vcoopsheejmrmdmlp95kpd1ge9gp08ih.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceFinalYearProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxnNrDRlhZ_ZEQr4y52XvnAtfFyLCtiT0',
    appId: '1:913978065914:ios:3ac347ddefafa87eb35a43',
    messagingSenderId: '913978065914',
    projectId: 'ecommerce-app-c97b9',
    storageBucket: 'ecommerce-app-c97b9.firebasestorage.app',
    androidClientId: '913978065914-hbc57tjs6nmmjsp2ipdcjrgtlq1au7en.apps.googleusercontent.com',
    iosClientId: '913978065914-vcoopsheejmrmdmlp95kpd1ge9gp08ih.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceFinalYearProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3DONa2lwALDtCeHoYOgjf2ClgvEIh6Z0',
    appId: '1:913978065914:web:f592a9e2e129ce4eb35a43',
    messagingSenderId: '913978065914',
    projectId: 'ecommerce-app-c97b9',
    authDomain: 'ecommerce-app-c97b9.firebaseapp.com',
    storageBucket: 'ecommerce-app-c97b9.firebasestorage.app',
    measurementId: 'G-K65Q7N6R1L',
  );

}